# Generated by Django 4.2.2 on 2023-06-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.TextField()),
                ('spring', models.TextField()),
                ('summer', models.TextField()),
                ('autumn', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='new', max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('beauty_title', models.TextField()),
                ('title', models.TextField()),
                ('other_titles', models.TextField()),
                ('connect', models.TextField()),
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_app.coordinates')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.level')),
                ('user_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('data', models.CharField(max_length=255)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.pereval')),
            ],
        ),
    ]
